Adiciona componente Thumbnail
eduzz/houston pull request #314
Opened 2022-05-14 21:52 UTC by miguelaugl

Galera, criei o componente Thumbnail, também tomei liberdade para tomar algumas decisões:

- Defini o tamanho padrão para medium, já que no Avatar está como medium também;
- Adicionei uma prop chamada fallbackSrc para que o usuário possa informar uma imagem enquanto a principal não está carregada ou se houve algum problema no carregamento.
- Inclui uma prop chamada fit porque dependendo do contexto o `object-fit` de uma imagem é muito necessário, principal no nosso caso que o aspect ratio é apenas de 1:1;

Concordam com esses pontos? Adicionaria ou removeria algo? Comentem <3

2022-05-14 21:54 UTC, danieloprado commented
Vai descansar hoje é sábado 🤫

2022-05-16 13:17 UTC, danieloprado requested changes

2022-05-16 13:56 UTC, ffernandomoraes commented on src/pages/ui-components/Thumbnail/index.tsx
> +          fit && `--${fit}`
Tava pensando em um caso de uso onde o `object-fit` seria necessário em um aspect ratio de 1:1, e acredito que não tenha né?!

Mas enfim, acho bom ter hahah 

Acho que um valor default não é necessário.

2022-05-16 13:56 UTC, ffernandomoraes approved these changes

2022-05-16 14:34 UTC, miguelaugl commented on src/pages/ui-components/Thumbnail/index.tsx
> +          fit && `--${fit}`
> Tava pensando em um caso de uso onde o `object-fit` seria necessário em um aspect ratio de 1:1, e acredito que não tenha né?!
> 
> Mas enfim, acho bom ter hahah
> 
> Acho que um valor default não é necessário.

Se liga nesse exemplo @ffernandomoraes, a imagem que eu informei não tem o aspect ratio de 1:1, mas com o `object-fit` a gente consegue utilizar ela melhor em diversos contextos:
![image](https://user-images.githubusercontent.com/58918493/168617334-dbb196e3-3a7d-4b9f-b19e-2f580d64230e.png)

2022-05-17 18:18 UTC, merged