Atualiza padrão de unidade de tokens e componentes para REM
eduzz/houston pull request #320
Opened 2022-05-18 04:37 UTC by miguelaugl

Galera, segue o PR que atualiza nosso padrão de PX para REM.

2022-05-19 15:03 UTC, danieloprado requested changes
Gostei de já colocar o rem como base, por mim funciona melhor.

2022-05-19 15:03 UTC, danieloprado commented on src/pages/ui-components/Table/styles.tsx
> +        margin-top: ${({ theme }) => (Number(theme.spacing.nano.replace('rem', '')) * 16 + 2) * -1}px;
acredito que aqui deveria usar o remToPx ou talvez criar um remToPxNumber?

2022-05-19 15:03 UTC, danieloprado commented on src/pages/ui-components/ThemeProvider/_generator/typography.ts
> +}
esse cara é outro caso de usado remToPxNumber (nome pode mudar kk)

2022-05-19 16:39 UTC, miguelaugl commented on src/pages/ui-components/Table/styles.tsx
> +        margin-top: ${({ theme }) => (Number(theme.spacing.nano.replace('rem', '')) * 16 + 2) * -1}px;
o remToPx retorna ele em string tipo `1rem`, é que a ideia é não usar o px mais né, então essa matemática não devia existir, só mantive assim por receio de quebrar algo

2022-05-20 11:24 UTC, ffernandomoraes commented
Este PR está pronto?

2022-05-20 13:28 UTC, miguelaugl commented
> Este PR está pronto?

Acredito que sim.

2022-05-23 14:14 UTC, merged