Refactor/toastr
eduzz/houston pull request #323
Opened 2022-05-21 00:37 UTC by phelpa

Criei um <ToastBody /> que vai ser o corpo do Toastr, este está tokenizado e de acordo com o design.

Alterei o jeito que usamos o react-toastify para só chamar o ToastBody e mais nada, pra deixar um mais responsável por fazer o toast popar na tela e o outro responsável pelo html/css.

Aproveitei e arranquei muitas classes já que agora o ToastBody que contém o css.

2022-05-23 06:54 UTC, miguelaugl commented on src/pages/ui-components/Toast/Container.tsx
> +          box-shadow: 0px 8px 24px rgba(0,0,0, 0.16);
Nesse caso você pode usar o useHoustonTheme e colocar as variáveis dos tokens aqui também.

2022-05-23 06:54 UTC, miguelaugl commented on src/pages/ui-components/Toast/Icons/index.tsx
> +  <svg width='192' height='192' viewBox='0 0 192 192' fill='none' xmlns='http://www.w3.org/2000/svg'>
Esses svgs estão muito grandes, será que não é melhor pedir pro design mandar o tamanho que é usado ao invés de diminuir pra esses casos?

2022-05-23 06:55 UTC, miguelaugl commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +interface IToastBody extends IStyledProp {
Complementaria essas interfaces com o sufixo `Props`, ou seja, `IToastBody -> IToastBodyProps`, só pelo padrão mesmo

2022-05-23 06:56 UTC, miguelaugl commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +  type: IToastBody['type'];
Ao invés de pegar de outra interface, você poderia criar um type chamado ToastTypes com os valores acima

2022-05-23 07:02 UTC, miguelaugl commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +      max-width: ${theme.pxToRem('370px')};
Aqui dando uma olhada no handoff fiquei um pouco em dúvida, nos casos que tem 2 linhas, ou seja, nos casos em que o toast está maior a width marcava 391px

2022-05-23 07:03 UTC, miguelaugl commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +      margin: 0 ${theme.spacing.inline.nano};
Seguindo o handoff o token está aplicado corretamente, porém visualmente ele não está batendo, poderia confirmar com algum design se aquele espaço extra além da margem descrita deveria ser inclusa?

2022-05-23 07:06 UTC, miguelaugl commented on src/pages/ui-components/Toast/styles.ts
>  .Toastify__toast-container--top-right {
Aqui acho que faltou considera os posicionamentos top e right conforme o handoff

2022-05-23 07:07 UTC, miguelaugl commented on src/pages/ui-components/Toast/Container.tsx
> +          box-shadow: 0px 8px 24px rgba(0,0,0, 0.16);
PS: Aparentemente o token de shadow não está funcionando porque o formato dele o css não aceita, na branch que tá pra ser mergeada corrige isso.

2022-05-23 07:08 UTC, miguelaugl requested changes
Boa mano, gostei muito da ideia do ToastBody, segue meu review com alguns pontos e sugestões. Qualquer coisa só chamar ;)

2022-05-23 13:20 UTC, phelpa commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +      margin: 0 ${theme.spacing.inline.nano};
Vejo sim

2022-05-23 14:07 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/Icons/index.tsx
> +  <svg width='192' height='192' viewBox='0 0 192 192' fill='none' xmlns='http://www.w3.org/2000/svg'>
É padrão esse tamanho (192px), todos os ícones estão assim. Mas isso não interfere em nada, besteira perder tempo com isso.

2022-05-23 14:13 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/Container.tsx
> +        autoClose={1000}
Foi decisão do designer isso? Fechar automaticamente em 1 segundo?

2022-05-23 14:13 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/Container.tsx
> +        limit={1}
Foi decisão do designer isso?

2022-05-23 14:13 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +const InitialIcon = ({ type }: IInitialIcon) => {
Hm não sei se curto muito esse switch case, será que um código assim não ficaria mais legal?

```ts
const iconsMap = {
  x: <xpto />,
  y: <xpto />,
  z: <xpto />
}

const initialIcon = ({ icon }) => iconsMap[icon];
```

2022-05-23 14:21 UTC, ffernandomoraes commented
@phelpa se você identificar algum valor que está em Pixel que pode ser alterado para REM (dentro do contextod o Toast), manda bala.

2022-05-23 14:50 UTC, miguelaugl commented on src/pages/ui-components/Toast/Container.tsx
> +        limit={1}
Boa Fer, tinha esse ponto aqui que eu esqueci de levantar, no handoff tinha que era no máximo 2

2022-05-23 15:03 UTC, miguelaugl commented on src/pages/ui-components/Toast/Icons/index.tsx
> +  <svg width='192' height='192' viewBox='0 0 192 192' fill='none' xmlns='http://www.w3.org/2000/svg'>
Segue com isso então mesmo @phelpa

2022-05-23 17:11 UTC, phelpa commented on src/pages/ui-components/Toast/Container.tsx
> +        autoClose={1000}
Não. Coloquei ai mas preciso conversar com eles.

2022-05-23 17:13 UTC, phelpa commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +const InitialIcon = ({ type }: IInitialIcon) => {
boa

2022-05-23 23:23 UTC, phelpa commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +      margin: 0 ${theme.spacing.inline.nano};
Conversei e o token foi alterado para incluir o espaço extra

2022-05-23 23:24 UTC, phelpa commented on src/pages/ui-components/Toast/Container.tsx
> +        autoClose={1000}
Conversei com o Milton e vamos deixar os 4 segs de antes

2022-05-23 23:59 UTC, phelpa commented on src/pages/ui-components/Toast/Container.tsx
> +          box-shadow: 0px 8px 24px rgba(0,0,0, 0.16);
Feito

2022-05-23 23:59 UTC, phelpa commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +      max-width: ${theme.pxToRem('370px')};
Feito

2022-05-24 00:00 UTC, phelpa reviewed
Feito todas as mudanças solicitadas

2022-05-24 01:14 UTC, miguelaugl commented on src/pages/ui-components/Toast/Container.tsx
> +          min-height: ${theme.pxToRem(10)};
Mano, aqui falta adicionar rem no final, ele converte somente os valores mas não adiciona o sufixo `rem`.

2022-05-24 12:47 UTC, phelpa commented on src/pages/ui-components/Toast/Container.tsx
> +          min-height: ${theme.pxToRem(10)};
> Mano, aqui falta adicionar rem no final, foi alterado e agora ele converte somente os valores mas não adiciona o sufixo `rem`. Se possível atualizar nos outros lugares que você utilizou essa função.

feito

2022-05-24 20:19 UTC, miguelaugl approved these changes
Boa, Plinião, mandando muitoow

2022-05-24 23:54 UTC, phelpa commented
> Boa, Plinião, mandando muitoow

✌️🥰❤️

2022-05-25 18:51 UTC, ffernandomoraes commented
Removi alguns estilos que não estavam sendo utilizados.

Estou aguardando a volta do Milton para validar alguns pontos relacionados a tamanhos dos ícones.

Da parte do código, está MUITO bom! Parabens para todos.

2022-06-06 22:09 UTC, phelpa commented
Atualizei de acordo com o novo design e também o modo mobile

2022-06-06 22:21 UTC, ffernandomoraes reviewed
Cara eu tinha feito uma limpa nos estilos, você puxou essas alterações?!

2022-06-06 22:21 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/Icons/index.tsx
> +export const InformativeIcon = () => (
Cara, estamos colocando a tag focusable nos svg por conta de outras libs utilizarem e por esse documento: https://allyjs.io/tutorials/focusing-in-svg.html . Seria legal manter esse padrão.

2022-06-06 22:21 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +  type: ToastTypes;
Esta propriedade não pode ser opicional e conter um valor padrão?

2022-06-06 22:21 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/ToastBody/index.tsx
> +    border-style: solid;
Não seria melhor unificar em um propriedade CSS? 

border: ${theme.border.width.xs} solid {COR_DEFAULT}.

2022-06-06 22:21 UTC, ffernandomoraes commented on src/pages/ui-components/Toast/Container.tsx
> +          ${isMobile ? 'margin: auto' : 'margin-left: auto'};
boa!!!!

2022-06-06 22:22 UTC, ffernandomoraes commented
No mais, está muito bom! To curtindo demais o nivel que estamos fazendo nossos componentes. Parabéns por participar dessa evolução ❤️

2022-06-07 13:39 UTC, phelpa commented
> Cara eu tinha feito uma limpa nos estilos, você puxou essas alterações?!

eu voltei pra versão antiga por causa do toastr no mobile que precisa ser bottom-center, ele não estava funcionando sem os css. Mas vou ir limpando e testando agora pra ver se não quebra nenhum caso.

2022-06-08 03:56 UTC, merged