Refatoração Alert
eduzz/houston pull request #332
Opened 2022-05-30 19:37 UTC by ffernandomoraes

Adicionei mais alguns recursos para nos ajudar:
- Expus o `CSSInterpolation`
- Abstrai a função `cleanUnit`
- Adicionei a prop `line-height` no Paragraph.

Um ponto para levar em consideração:
- No figma o valor do token `theme.spacing.stack.xxs` está com o valor de `1rem`, no código o mesmo é igual a `1.5rem`. Pode ter sido erro de digitação do handoff, mas vou validar com algum designer.

Preview:
![screencapture-localhost-3000-houston-ui-components-Alert-2022-05-30-16_29_23 (1)](https://user-images.githubusercontent.com/22228470/171051165-356f6323-b8a2-4b59-8ce8-9ee7454f0ea2.png)

2022-05-31 16:37 UTC, phelpa approved these changes

2022-05-31 21:32 UTC, miguelaugl requested changes

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +    if ((!controlled && !visible) || (controlled && !visibleProp)) {
Achei esse trecho muito confuso. Você pode criar uma variável chamada isVisible dessa forma: `const isVisible = controlled ? visibleProp : visible` e dessa forma tudo que depender do visible olha pra essa prop pra evitar confusões.

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +              <div className='__title'>
Aqui por que não usar o Typography direto ao invés de criar essa div extra?

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.mdx
> +| visible     | `boolean`         | `false`     | `true`        | Controle de exibição.                  |
A prop é falsy, o state interno do visible é true

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.mdx
> +| type        | `AlertTypes`      | `false`     | `informative` | -                                      |
Ao invés de informar AlertTypes, fica melhor colocar todos os tipos separados

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +          <span role='img' className='__close' onClick={handleClose}>
Aqui acho que a role=button seria mais apropriado do que a role=img, também adicionaria um aria-label='Fechar alerta' ou algo parecido

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +                <Typography.Heading color='neutralColor.low.pure' as='h5' lineHeight='default'>
Aqui acho que h5 não é a melhor opção.
Chequei em 4 design system e ninguém usa o título como heading, usam logo como div, talvez tenha um motivo bom mas confesso que não sei.

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.mdx
> +| actionText  | `React.ReactNode` | `false`     | -             | -                                      |
Aqui seria bom especificar que se informado é exibido o botão

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +  /**
Esse comentário dessa forma chega pro usuário final, será que essa mensagem tá bem descrita?

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.tsx
> +      onClose && onClose();
Será que não é legal passar o evento do click pra esse onClose?

2022-05-31 21:32 UTC, miguelaugl commented on src/pages/ui-components/Alert/index.mdx
> +  <Alert actionText='Ação customizada' actionProps={{ onClick: () => alert('Houston ❤️') }}>
Por que só um coração? kkkkk brincadeira

2022-06-01 00:19 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.tsx
> +    if ((!controlled && !visible) || (controlled && !visibleProp)) {
Não acho confuso, está simples. Mas opção parece mais simples ainda, vou aderir.

2022-06-01 00:23 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.tsx
> +              <div className='__title'>
Por que o title aplica margins diferentes nas resoluções. Eu poderia passar essa classe pro Typography, mas acho que não é tão relevante.

2022-06-01 00:28 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.mdx
> +| type        | `AlertTypes`      | `false`     | `informative` | -                                      |
O quanto relevante isso seria? 

Pra mim é mais trabalhoso e sem nenhum ganho expressivo. Por que se algum for removido/adicionado algum type, teriamos que atualizar a doc também. E isso sempre da brecha para esquecimentos.

Indo mais além, na documentação do Typography prop `color`, deveríamos colocar todos os valores possíveis?

Enfim, acredito que seja desnecessário, quem for implementar vai se deparar com os valores reais no código.

2022-06-01 00:45 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.tsx
> +          <span role='img' className='__close' onClick={handleClose}>
Segundo o antd, é `img` mesmo hehe

Sobre a prop `aria-label`, acho melhor conversamos sobre para adotarmos um padrão juntos. Se vai ser BR, En, quando usar e etc...

2022-06-01 00:46 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.tsx
> +      onClose && onClose();
Pode ser

2022-06-01 00:49 UTC, ffernandomoraes commented on src/pages/ui-components/Alert/index.tsx
> +                <Typography.Heading color='neutralColor.low.pure' as='h5' lineHeight='default'>
Vou verificar, acho que em algum lugar do design vi algo com h5, por isso coloquei.

2022-06-01 14:12 UTC, merged

2022-06-02 16:14 UTC, Notlim38 commented
Boa tarde. 
Desculpem demora em responder. Estou me recuperando e voltei hoje a ativa. 
Mas vamos lá. Acredito que na folha de tokens q passamos esteja o valor correto, no entanto, neste arquivo do Google Drive, não foram passados os valores em REM. Mas, no Figma existe essa equivalência descrita. Como nas imagens em anexo.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/100154664/171675766-fa66faad-64d5-412d-9b6d-1838d8d39a1b.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/100154664/171675885-d4178fbd-e58c-4836-abd3-705a5a1d6335.png">