Novo componente de Search
eduzz/houston pull request #363
Opened 2022-07-07 19:06 UTC by miguelaugl

Não sei, não estou muito satisfeito, estou sentindo que está faltando algo 🤔 

![image](https://user-images.githubusercontent.com/58918493/177851970-29e819bd-29da-42e7-9d67-ee14d38bbc9b.png)
![image](https://user-images.githubusercontent.com/58918493/177852011-012eb89c-7a10-4a98-8810-329303e1ceb5.png)

Figma: https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/?node-id=1791%3A35492

2022-07-11 14:31 UTC, phelpa commented on src/pages/ui-components/Popover/Root.tsx
> +  });
Qual foi a ideia dessas mudanças? quero entender mesmo

2022-07-11 16:16 UTC, ffernandomoraes requested changes

2022-07-11 16:16 UTC, ffernandomoraes commented on src/pages/ui-components/Forms/Search/Result.tsx
> +  function handleClick() {
essa função foge do nosso padrão, masssss

2022-07-11 16:16 UTC, ffernandomoraes commented on src/pages/ui-components/Forms/Search/context.tsx
> +    throw new Error('You must provide a `SearchContextProvider` in order to use `useSearch`');
hm, do mesmo jeito que existe a função `warn`, poderia ter uma função `error` né? hehe

2022-07-11 16:16 UTC, ffernandomoraes commented on src/pages/ui-components/Forms/Search/index.tsx
> +  const isSubmitting = useFormIsSubmitting();
Realmente.

2022-07-11 16:16 UTC, ffernandomoraes commented on src/pages/ui-components/Forms/Search/index.tsx
> +      onEnter?.(value, e);
🤢

2022-07-14 19:50 UTC, ffernandomoraes approved these changes

2022-07-15 00:03 UTC, danieloprado commented
Tem conflito, acho que vai precisar mexer pois o esquema do form mudou.

2022-07-17 13:29 UTC, danieloprado commented on src/pages/ui-components/hooks/useOnClickOutside.tsx
> +  ref: React.RefObject<T>,
por que foi alterado a tipagem? antes permitia passar um htmlelement.

2022-07-20 18:33 UTC, phelpa approved these changes

2022-07-20 18:33 UTC, merged