refactor: change Icon
eduzz/houston pull request #366
Opened 2022-07-12 20:45 UTC by miguelaugl

Atualização dos ícones:
- Não temos mais o wrapper do span;
- Os tamanhos só podem ser 3;
- Padronizado de acordo com o que esperamos (tokens, BEM, etc).

Preview: 

![image](https://user-images.githubusercontent.com/58918493/178591827-deaf9763-cfe4-44fe-a046-5a52cb58c203.png)

2022-07-13 18:20 UTC, phelpa approved these changes
Achei muito top o jeito que você fez, em deixar um componente pai como ```<svg>```

Desse jeito dá pra gente customizar e ter um padrão nosso no ```<svg>``` e os paths seriam somente os desenhos. Boa!

2022-07-14 19:48 UTC, ffernandomoraes approved these changes

2022-07-14 23:54 UTC, danieloprado commented
Acho que pode ter esses tamanhos, mas acho que deveria tambem deixar a opção de numero, nao vejo por que proibir. E deixamos os svgs fora do componente para podermos usar no react native por que do jeito que ta nao dá.

2022-07-14 23:55 UTC, danieloprado requested changes
Acho que precisamos discutir aqui ainda.

2022-07-15 14:13 UTC, ffernandomoraes commented
Testado e aprovado, aguardando a discussão sobre o React Native.

2022-07-15 19:09 UTC, merged