Refactor/list
eduzz/houston pull request #367
Opened 2022-07-12 21:07 UTC by phelpa

Changes :

**List:** 
Não tem mais stripedRows

**List.left:** 
Não tem mais image
Adicionado children

**List.right:**
Não tem mais text
Adicionado children

https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=715%3A19515

![image](https://user-images.githubusercontent.com/17049866/178595362-2d67ef07-c789-4716-b935-2128d51e9f5a.png)

2022-07-13 16:04 UTC, miguelaugl commented
Mano, acho que a implementação poderia ser diferente, algo como:
```tsx
<List
  // adiciona os dividers entre os itens
  dividers 
>
  <List.Item
       title='Título'
       subtitle='Texto qualquer'
       left={
        <Checkbox />
       }
       thumbnailProps={{
        src: '...',
        size: 'md'
       }}
      avatarProps={...}
      right={
        <FaceHappyIcon />
      }
  />
</List>
```

Porque ai você já define a posição dos elementos e etc, o que acha?

2022-07-13 16:41 UTC, phelpa commented
> Mano, acho que a implementação poderia ser diferente, algo como:
> 
> ```tsx
> <List
>   // adiciona os dividers entre os itens
>   dividers 
> >
>   <List.Item
>        title='Título'
>        subtitle='Texto qualquer'
>        left={
>         <Checkbox />
>        }
>        thumbnailProps={{
>         src: '...',
>         size: 'md'
>        }}
>       avatarProps={...}
>       right={
>         <FaceHappyIcon />
>       }
>   />
> </List>
> ```
> 
> Porque ai você já define a posição dos elementos e etc, o que acha?

Eu acho que se simplesmente deixar o List.Left e o List.Right aceitando children fica mais composable o componente e não quebraria o jeito atual da api, o seu exemplo ficaria : 
```tsx
<List>
  <List.Item>
     <List.Left> <Checkbox/><List.Left/>
     <List.Left> <Thumbnail img={....}/><List.Left/>
     <List.Left> <Avatar img={....}/><List.Left/>
     <List.Text title="Lorem Ipsum Dolor" subtitle="Lorem Ipsum Dolor" />
     <List.Right>
        <FaceHappyIcon /> //por mim deixaria só children e tiraria o icon
     <List.Right/>
    />
 <List.Item/>
 <Divider/>
 {...próx item}
 </List>
 ```
 
 Eu to vendo essa Lista mais como um posicionador em uma linha do que qualquer outra coisa, pelo children você passa o que você quer que fique posicionado ali naquele lugar, o design acredito estar apontado pra isso também porque tem muitas possibilidades.
  
 Sobre o divider vai ter algumas vezes que vocẽ vai querer ele em umas linhas e outras não como : 
 
 
![image](https://user-images.githubusercontent.com/17049866/178785386-da6676b5-ff0d-4875-9e96-425f8e564731.png)

Olha quantas coisas você pode passar para o List.Left ou List.Right : 

![image](https://user-images.githubusercontent.com/17049866/178785767-28aa5ca0-b78d-43ab-8cbf-bd39ca886593.png)

Enfim, eu to vendo esse componente da List mais como um agrupador de linhas (list.item) e o List.Item sendo uma linha genérica que serve para você posicionar quaisquer elementos dentro dela, ficando bem versátil.

2022-07-14 19:47 UTC, ffernandomoraes commented on src/pages/ui-components/List/Item/index.tsx
> +      {children}
Poderia remover esse `children` daqui e colocar dentro do `{...rest`} ia funcionar hehe

2022-07-14 19:47 UTC, ffernandomoraes commented on src/pages/ui-components/List/List.tsx
>  };
`const List = ({ ...rest }: IListProps) => <ul role='list' {...rest} />;`

2022-07-14 19:47 UTC, ffernandomoraes commented on src/pages/ui-components/List/List.tsx
> +const ListWrapper = React.memo(styled(List, { label: 'houston-list' })());
Se não ta usando estilo, pode remover o `styled`.

2022-07-14 19:47 UTC, ffernandomoraes commented on src/pages/ui-components/List/Item/index.tsx
> +export interface IListItemProps extends IStyledProp, React.HTMLAttributes<HTMLLIElement> {
Podemos remover os `I` inicial das interfaces, não fazem mais sentido e já foi removido do nosso eslint.

2022-07-14 19:47 UTC, ffernandomoraes commented on src/pages/ui-components/List/Left/index.tsx
> +    <div className={cx(className)} {...rest}>
pq aqui deixou com `cx`?

2022-07-14 23:50 UTC, danieloprado requested changes

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/context.ts
> +  dividers?: true;
Eu removeria e o ?, e na criação do contexto ali embaixo passaria o { dividers: false }, é mais por garantia.

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/Text/index.tsx
>    subtitle?: string | React.ReactNode;
Nao necessidade do string aqui, por que o ReactNode já tem string dentro. Tem a necessidade do ReactNode? nao seria melhor só string, nao sei da especificação kkk

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/List.tsx
> +    <ListContextProvider value={{ dividers }}>
é sempre bom colocar o context value em um useMemo, para nao recriar toda hora o objeto.

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/List.tsx
> +const ListWrapper = React.memo(styled(List, { label: 'houston-list' })());
nao vejo a necessidade do memo aqui, o componente é bem simples

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/Left/index.tsx
> +export default React.memo(
nao precisa do memo, componente é muito simples.

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/Right/index.tsx
> +export default React.memo(
nao precisa do memo, componente é muito simples e está com o nome errado kk

2022-07-14 23:50 UTC, danieloprado commented on src/pages/ui-components/List/Text/index.tsx
> +export default React.memo(styled(ListText, { label: 'houston-list-text' })());
nao precisa do memo, componente é muito simples.

2022-07-15 18:07 UTC, ffernandomoraes approved these changes

2022-07-15 18:07 UTC, merged