Feat/accordion
eduzz/houston pull request #423
Opened 2022-08-23 18:13 UTC by phelpa

![image](https://user-images.githubusercontent.com/17049866/186231647-1e9f75fc-8921-4670-8df5-16278148d2f4.png)

figma : https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=3441%3A68923

api :

```jsx
<Accordion>
  <Accordion.Item>
    <Accordion.Title>Title 1</Accordion.Title>
    <Accordion.Content>
      <div>Conteúdo 1</div>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item>
    <Accordion.Title>Title 2</Accordion.Title>
    <Accordion.Content>
      <div>Conteúdo 2</div>
    </Accordion.Content>
  </Accordion.Item>
  <Accordion.Item>
    <Accordion.Title>Title 3</Accordion.Title>
    <Accordion.Content>
      <div>Conteúdo 3</div>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>
 ```
 
Eu criei uma array 'cachedItems', pra quando o cara abrir um item eu salvar nessa array que ele já foi aberto pelo menos uma vez, assim se o cara clicar de novo no item ele não vai re-renderizar o componente, dessa forma se esse componente filho do item faz vários requests ele não vai fazer de novo.  O accordion dos produtos do orbita sofre desse problema, ele refaz os requests toda hora que você abre o item.

Se o cara não quiser esse comportamento só mandar um 'destroyOnClose' e boa.

2022-08-25 14:08 UTC, ffernandomoraes requested changes
Cara, ficou bem legal o componente, mas tenho alguns pontos:

1- Tudo onde estiver `useAccordion()`, `useItemId()`, deve ser alterado para a sintaxe individual. Por que? Cada vez que você faz isso, qualquer prop que for alterada dentro do contexto, vai causar re-render em tudo o que estiver olhando pra esse `hook`. Então não faria sentido usar o `useContextSelector`... 
![image](https://user-images.githubusercontent.com/22228470/186685792-d40d982c-35c1-4227-9793-4249b2b42e43.png)

2 - Toda essa parte de cacheItems eu não entendi, por que quem deve controlar se o conteúdo vai ser removido ou mantido no DOM é o Collpase (que já possui uma prop `destroyOnClose` que controla justamente isso). Então não entendi qual o valor desse recurso (cachedItems).

Dei uma testada por cima, e parece estar tudo OK. Funcionou bonitinho!!

2022-08-25 14:52 UTC, miguelaugl commented on src/dev/src/App.tsx
> +            <Group label='Aldair'>
Aldair

2022-08-25 16:35 UTC, phelpa commented
Entendi sobre o contexto, vou mudar, muito bom toque.

Sobre o cachedItems ele está servindo para que quando um componente que faz requests dentro do Item for aberto e depois for fechado, quando o usuário abrir esse item de novo ele não vai fazer os requests novamente (não vejo a necessidade).

Se eu tiro ele o que vai acontecer : todos os componentes dentro do Accordion que fazem requests vão ser feitos tudo de uma vez, imagina um accordion com 40 items, seriam 40 requests. 

Como está funcionando : O accordion é renderizado, e os contents (que estão dentro dos items) não são, quando eu abro um item ele daí vai renderizar aquele content que então vai fazer seus requests, e não vai fazer nunca mais porque agora eu 'cacheei'

Não precisaria disso em um cenário em que o componente tem dentro dele somente JSX (dumb component) porque nesse caso realmente não precisa 'cachear' mas se eu faço um request dentro dele, pra não precisar fazer esse request toda vez que o item é aberto eu fiz isso.

Posso ter me enganado e tem um jeito mais elegante de fazer isso, ou não há necessidade de fazer isso (eu tenho impressão que faz).

2022-08-25 16:38 UTC, phelpa commented
> Plínião, primeiramente, parabéns lindão <3, gostei mt
> 
> Segundamente dois pontos:
> 
> * Da forma como o código tá montado, aparentemente o cachedItems não tá fazendo nada, ele tá meio que fazendo o papel do destroyOnClose mas o destroyOnClose já tá ali, me corriga se eu estiver falando maluquices
> * Outra parada, cara, acho muito problemático a gente usar index como centro da lógica de algum componente, isso porque index é nada mais nada menos que a posição do array e no React a posição componente no DOM, vamos supor em um contexto onde a ordem dos accordion mude ou saia/entre um accordion novo no meio da lista, o DOM é geralmente mutável então o ideal seria o Item ter uma prop que tivesse seu próprio identificador e se não tiver, gerar um UUID pra ele. A prop pode se chamar key.

Expliquei melhor sobre o cachedItems no outro post. Vou dar mais uma olhada no código para verificar se ele está fazendo um papel desnecessário.

Sobre usar index eu fui na onda do Tabs que era assim e o chakra também faz dessa forma. Mas tudo que você falou é relevante, acho que deveríamos discutir melhor isso ai e bater o martelo se for realmente necessário.

2022-08-25 16:40 UTC, phelpa commented on src/dev/src/App.tsx
> +            <Group label='Aldair'>
hahuahua é meu nome pra testes, acabei deixando :X

2022-08-26 02:53 UTC, ffernandomoraes approved these changes

2022-08-26 02:53 UTC, merged