Feat/stepper
eduzz/houston pull request #448
Opened 2022-09-15 22:49 UTC by phelpa

![image](https://user-images.githubusercontent.com/17049866/190296082-bd2c5e1c-6d69-4bb4-b5d5-7decede3337a.png)

![image](https://user-images.githubusercontent.com/17049866/190521874-dae5cb6b-38c3-4eaa-aa74-37b67020b4d3.png)

Figma :  https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Core-components-handoff?node-id=5200%3A103110

```jsx
    const [current, setCurrent] = React.useState(1);
    return (
      <Stepper current={current} onPrev={current => setCurrent(current)} onNext={current => setCurrent(current)}>
        <Step label='Básico'>
          <div>Conteúdo1</div>
        </Step>
        <Step label='Personalização' description='Personalize seu produto'>
          <div>Conteúdo2</div>
        </Step>
        <Step label='Comunicação' error description='Comunicação é muito importante'>
          <div>Conteúdo3</div>
        </Step>
        <Step label='Avançado'>
          <div>Conteúdo4</div>
        </Step>
      </Stepper>
    );
```

### Stepper props

| prop           | type               | required | default | description                                                                                |
| -------------- | ------------------ | -------- | ------- | ------------------------------------------------------------------------------------------ |
| onPrev         | `(number) => void` | `false`  | -       | Passa pelo callback o índice do Step                                                       |
| onNext         | `(number) => void` | `false`  | -       | Passa pelo callback o índice do Step                                                       |
| current        | `number`           | `false`  | `false` | Índice do Step atual                                                                       |
| children       | `React.ReactNode`  | `true`   | -       |                                                                                            |
| noClick        | `boolean`          | `false`  | `false` | Desabilita o click no Step                                                                 |
| destroyOnClose | `boolean`          | `false`  | `false` | Se true o componente que está dentro do Step será desmontado depois que o Step for trocado |
| mountOnEnter   | `boolean`          | `false`  | `false` | Se true o componente que está dentro do Step só será montado depois que o Step for trocado |

### Step props

| prop        | type              | required | default | description |
| ----------- | ----------------- | -------- | ------- | ----------- |
| children    | `React.ReactNode` | `false`  | -       |             |
| error       | `boolean`         | `false`  | `false` |             |
| label       | `string`          | `true`   | -       |             |
| description | `string`          | `false`  | -       |             |

2022-09-22 04:24 UTC, ffernandomoraes commented on src/pages/ui-components/IconButton/index.tsx
> +          { '--hst-icon-content-disabled': disabled },
o que são esses `--` ein?

2022-09-23 14:08 UTC, ffernandomoraes requested changes
Analisando aqui, precisa realmente ter esses 4 componentes de botões? Olhando superficialmente, parece que um modificador seria o suficiente, não acha?

2022-09-23 14:56 UTC, phelpa commented on src/pages/ui-components/IconButton/index.tsx
> +          { '--hst-icon-content-disabled': disabled },
antigamente usávamos --disabled, só continuei fazendo o mesmo agora com o prefixo, posso mudar

2022-09-23 15:02 UTC, phelpa commented on src/pages/ui-components/IconButton/index.tsx
> +          { '--hst-icon-content-disabled': disabled },
> Analisando aqui, precisa realmente ter esses 4 componentes de botões? Olhando superficialmente, parece que um modificador seria o suficiente, não acha?

Cara olhando aqui acho que dá pra deixar 4 ícones de botões e manter o mesmo html com modificadores

2022-09-23 15:02 UTC, phelpa commented on src/pages/ui-components/Stepper/index.tsx
> +  noClick?: boolean;
> Analisando aqui, precisa realmente ter esses 4 componentes de botões? Olhando superficialmente, parece que um modificador seria o suficiente, não acha?

Cara olhando aqui acho que dá pra deixar 4 ícones de botões e manter o mesmo html com modificadores

2022-09-27 18:23 UTC, phelpa commented on src/pages/ui-components/Stepper/index.tsx
> +  const childrenProps = useChildrenProps(children, Step);
Com a api atual não teve como fugir dele :/

2022-10-09 16:46 UTC, ffernandomoraes commented
Obrigado pela contribuição, mas não faz mais sentido pro projeto, PR fechada.

2022-10-09 16:46 UTC, closed without merging