Feat/add use media query hook
eduzz/houston pull request #474
Opened 2023-03-20 18:00 UTC by miguelaugl

Muitos componentes que têm alguma tratativa por tamanho de tela está criando a necessidade desse hook e para não precisar criar em todos projetos adicionei no houston

2023-03-20 18:02 UTC, danieloprado commented
@miguelaugl seria possivel criar um com os tamanhos pré-definifos tambem? tipo `useMediaBreakpoint`

2023-03-20 18:03 UTC, miguelaugl commented
> @miguelaugl seria possivel criar um com os tamanhos pré-definifos tambem? tipo `useMediaBreakpoint`

Crio um outro hook ou aceito passar uma callback que passa o theme?

2023-03-20 18:07 UTC, danieloprado requested changes

2023-03-20 18:07 UTC, danieloprado commented on src/pages/hooks/useMediaQuery/index.tsx
> +  const getMatches = (query: string): boolean => {
move ele para fora da função, nao tem necessidade de estar dentro.

2023-03-20 18:07 UTC, danieloprado commented on src/pages/hooks/useMediaQuery/index.tsx
> +  const [matches, setMatches] = useState(getMatches(query));
useState(() => getMatches(query)); // só roda uma vez

2023-03-20 18:07 UTC, danieloprado commented on src/pages/hooks/useMediaQuery/index.tsx
> +  function handleChange() {
moveria para dentro do useEffect como uma const

2023-03-21 14:16 UTC, ffernandomoraes approved these changes

2023-03-21 16:43 UTC, danieloprado approved these changes

2023-03-22 14:34 UTC, merged