Criando o componente lista
eduzz/houston pull request #48
Opened 2021-03-22 21:52 UTC by miguelaugl

Usei o mesmo padrão para criação deste componente utilizado nas Tabs e Tables, porque foi com ele que tive mais liberdade para manipular o DOM e dessa forma atingir o design do Figma.

Adicionei mais e mudei alguns detalhes em relação ao último comentário na issue.

Vejam com carinho <3

[]s

2021-03-22 22:20 UTC, ffernandomoraes commented
Mudar o destino para branch ´develop´.

2021-03-23 12:56 UTC, danieloprado requested changes
Deixe uns comentários lá no código! qualquer duvida só me chamar 👌

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/List.tsx
> +      <ListContextProvider value={contextValue}>
Acho que não necessário o ContextAPI, pode passar as props direto pro <Items /> assim ganha um render a menos. O ContextAPI só é interessante quando não da para saber quando o Children vai aparecer, nesse caso ele já esta direto ao pai.

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Items/index.tsx
> +              key={`list-item-${index}-left`}
A prop key só é necessário no filho direto do map, no caso o ListItemMUI, nos outros ela não surte efeito nenhum.

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Left/index.tsx
> +  if (!icon && image) {
Você já verificou se o icon existe no if de cima, então não precisa verificar novamente, e terá um terceiro cenário? se não acho que pode matar o else do ternário.

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Right/index.tsx
> +    if (onClick) {
não é legar ter 2 níveis de if, melhor seria se fosse um if para cada, if(icon && onClick) e depois um if(icon)

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Right/index.tsx
> +  if (!icon && text) {
e não precisa verificar novamente o icon aqui se já verificou ele em cima

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Title/index.tsx
> +    <TypographyMUI {...props} className={clsx([classes.root])}>
pode colocar direto o className={classes.root} o clsx é para múltiplas classes.

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Subtitle/index.tsx
> +    <TypographyMUI {...props} className={clsx([classes.root])}>
pode colocar direto o className={classes.root} o clsx é para múltiplas classes.

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Title/index.tsx
> +import TypographyMUI from '@material-ui/core/Typography';
use o typography do Houston. Talvez até mate o useStyles ali embaixo

2021-03-23 12:56 UTC, danieloprado commented on packages/ui-components/List/internals/Subtitle/index.tsx
> +import TypographyMUI from '@material-ui/core/Typography';
use o typography do Houston. Talvez até mate o useStyles ali embaixo

2021-03-23 16:42 UTC, ffernandomoraes requested changes

2021-03-23 16:42 UTC, ffernandomoraes commented on packages/ui-components/List/internals/Right/index.tsx
> +  if (icon) {
Essas duas condições estão meio estranhas. Se tiver o `icon`, não vai chegar na segunda condição.

2021-03-23 16:42 UTC, ffernandomoraes commented on packages/ui-components/List/README.md
> +# Lista
Já temos o projeto de documentação (/docs), não rola de fazer a documentação lá?

2021-03-24 21:34 UTC, miguelaugl commented
Mudei as coisinhas que você pediram, podem revalidar?

2021-03-25 12:14 UTC, danieloprado approved these changes

2021-03-25 12:14 UTC, merged